# Generated by Django 5.2.1 on 2025-09-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['department', '-level', 'code'], 'verbose_name': '职位', 'verbose_name_plural': '职位'},
        ),
        migrations.AddField(
            model_name='position',
            name='management_level',
            field=models.CharField(choices=[('senior', '高层'), ('middle', '中层'), ('junior', '基层')], default='junior', max_length=20, verbose_name='管理层级'),
        ),
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.IntegerField(choices=[(13, '高层正职'), (12, '高层副职'), (11, '高层助理'), (9, '中层正职'), (8, '中层副职'), (7, '中层助理'), (4, '基层正职'), (3, '基层副职'), (2, '基层助理'), (1, '员工')], default=1, verbose_name='职位级别'),
        ),
    ]
