# Generated by Django 5.2.1 on 2025-09-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0002_alter_position_options_position_management_level_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ["-level", "code"],
                "verbose_name": "职位",
                "verbose_name_plural": "职位",
            },
        ),
        migrations.AlterField(
            model_name="position",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="organizations.department",
                verbose_name="所属部门",
            ),
        ),
    ]
