# Generated by Django 5.2.1 on 2025-09-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_remove_position_department_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('management_level', models.CharField(choices=[('senior', '高层'), ('middle', '中层'), ('junior', '基层')], max_length=20, verbose_name='管理层级')),
                ('level', models.IntegerField(choices=[(13, '高层正职'), (12, '高层副职'), (11, '高层助理'), (9, '中层正职'), (8, '中层副职'), (7, '中层助理'), (4, '基层正职'), (3, '基层副职'), (2, '基层助理'), (1, '员工')], verbose_name='职位级别')),
                ('default_requirements', models.TextField(blank=True, verbose_name='默认任职要求')),
                ('default_responsibilities', models.TextField(blank=True, verbose_name='默认岗位职责')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '职位模板',
                'verbose_name_plural': '职位模板',
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('category', models.CharField(choices=[('organization', '组织架构配置'), ('position', '职位配置'), ('employee', '员工配置'), ('workflow', '工作流配置'), ('integration', '集成配置'), ('security', '安全配置'), ('notification', '通知配置')], max_length=20, verbose_name='配置分类')),
                ('description', models.TextField(blank=True, verbose_name='配置描述')),
                ('data_type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('boolean', '布尔值'), ('json', 'JSON对象'), ('list', '列表')], default='string', max_length=20, verbose_name='数据类型')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='是否加密')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必需')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('approval', '审批流程'), ('notification', '通知规则'), ('data_sync', '数据同步'), ('permission', '权限控制')], max_length=20, verbose_name='规则类型')),
                ('trigger_conditions', models.JSONField(default=dict, verbose_name='触发条件')),
                ('action_config', models.JSONField(default=dict, verbose_name='动作配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工作流规则',
                'verbose_name_plural': '工作流规则',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('employee_status', '员工状态'), ('position_type', '职位类型'), ('department_type', '部门类型'), ('education_level', '学历层次'), ('skill_level', '技能等级'), ('language', '语言类型'), ('nationality', '国籍'), ('marital_status', '婚姻状况'), ('custom', '自定义')], max_length=50, verbose_name='字典分类')),
                ('code', models.CharField(max_length=50, verbose_name='字典编码')),
                ('name', models.CharField(max_length=100, verbose_name='字典名称')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='字典值')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.dictionary', verbose_name='父级字典')),
            ],
            options={
                'verbose_name': '数据字典',
                'verbose_name_plural': '数据字典',
                'ordering': ['category', 'sort_order', 'code'],
                'unique_together': {('category', 'code')},
            },
        ),
    ]
