# Generated by Django 5.2.1 on 2025-09-25 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_apigateway_apiroute_apimonitor_integrationsystem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('permission_type', models.CharField(choices=[('read', '读取权限'), ('write', '写入权限'), ('delete', '删除权限'), ('export', '导出权限')], max_length=20, verbose_name='权限类型')),
                ('scope_type', models.CharField(choices=[('all', '全部数据'), ('dept', '本部门数据'), ('dept_and_child', '本部门及下级数据'), ('self', '本人数据'), ('custom', '自定义范围')], max_length=20, verbose_name='数据范围')),
                ('resource_type', models.CharField(max_length=100, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='资源ID')),
                ('custom_scope', models.JSONField(blank=True, default=dict, verbose_name='自定义范围')),
                ('field_permissions', models.JSONField(blank=True, default=dict, verbose_name='字段权限')),
                ('data_masking', models.JSONField(blank=True, default=dict, verbose_name='数据脱敏')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '数据权限',
                'verbose_name_plural': '数据权限',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='权限编码')),
                ('permission_type', models.CharField(choices=[('menu', '菜单权限'), ('button', '按钮权限'), ('api', 'API权限'), ('data', '数据权限'), ('field', '字段权限')], max_length=20, verbose_name='权限类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('resource', models.CharField(blank=True, max_length=200, verbose_name='资源标识')),
                ('action', models.CharField(blank=True, max_length=50, verbose_name='操作类型')),
                ('level', models.IntegerField(default=1, verbose_name='权限级别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.permission', verbose_name='父权限')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'ordering': ['level', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=200, unique=True, verbose_name='缓存键')),
                ('cache_data', models.JSONField(default=dict, verbose_name='缓存数据')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_cache', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '权限缓存',
                'verbose_name_plural': '权限缓存',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('grant', '授权'), ('revoke', '撤销'), ('inherit', '继承'), ('expire', '过期')], max_length=20, verbose_name='操作类型')),
                ('resource_type', models.CharField(max_length=100, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='资源ID')),
                ('action_detail', models.JSONField(default=dict, verbose_name='操作详情')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('denied', '拒绝')], max_length=20, verbose_name='操作结果')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '权限日志',
                'verbose_name_plural': '权限日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='角色编码')),
                ('role_type', models.CharField(choices=[('system', '系统角色'), ('custom', '自定义角色'), ('department', '部门角色')], default='custom', max_length=20, verbose_name='角色类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统角色')),
                ('level', models.IntegerField(default=1, verbose_name='角色级别')),
                ('inherit_permissions', models.BooleanField(default=True, verbose_name='继承父角色权限')),
                ('data_scope', models.CharField(choices=[('all', '全部数据权限'), ('custom', '自定义数据权限'), ('dept', '本部门数据权限'), ('dept_and_child', '本部门及以下数据权限'), ('self', '仅本人数据权限')], default='self', max_length=20, verbose_name='数据权限范围')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_roles', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.role', verbose_name='父角色')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, verbose_name='可查看')),
                ('can_edit', models.BooleanField(default=False, verbose_name='可编辑')),
                ('can_delete', models.BooleanField(default=False, verbose_name='可删除')),
                ('can_manage', models.BooleanField(default=False, verbose_name='可管理')),
                ('data_scope', models.CharField(choices=[('all', '全部数据'), ('dept', '本部门数据'), ('dept_and_child', '本部门及下级数据'), ('self', '本人数据')], default='self', max_length=20, verbose_name='数据范围')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_permissions', to='organizations.department', verbose_name='部门')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '部门权限',
                'verbose_name_plural': '部门权限',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'department')},
            },
        ),
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=100, verbose_name='资源类型')),
                ('field_name', models.CharField(max_length=100, verbose_name='字段名')),
                ('permission_type', models.CharField(choices=[('visible', '可见'), ('readonly', '只读'), ('hidden', '隐藏'), ('masked', '脱敏')], max_length=20, verbose_name='权限类型')),
                ('masking_rule', models.CharField(blank=True, max_length=100, verbose_name='脱敏规则')),
                ('masking_config', models.JSONField(blank=True, default=dict, verbose_name='脱敏配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '字段权限',
                'verbose_name_plural': '字段权限',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'resource_type', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='RoleDataPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_granted', models.BooleanField(default=True, verbose_name='是否授权')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('data_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_data_permissions', to='organizations.datapermission', verbose_name='数据权限')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='授权者')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_data_permissions', to='organizations.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色数据权限',
                'verbose_name_plural': '角色数据权限',
                'unique_together': {('role', 'data_permission')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_granted', models.BooleanField(default=True, verbose_name='是否授权')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='授权者')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='organizations.permission', verbose_name='权限')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='organizations.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='分配者')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='organizations.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
