# Generated by Django 5.2.1 on 2025-09-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_datapermission_permission_permissioncache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapermission',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]
