# Generated by Django 5.2.1 on 2025-09-29 03:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_datapermission_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='工作流名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分类')),
                ('nodes', models.JSONField(default=list, verbose_name='节点配置')),
                ('connections', models.JSONField(default=list, verbose_name='连接配置')),
                ('canvas_config', models.JSONField(default=dict, verbose_name='画布配置')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '激活'), ('inactive', '停用'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('current_version', models.CharField(default='v1.0.0', max_length=50, verbose_name='当前版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('execution_count', models.IntegerField(default=0, verbose_name='执行次数')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='成功率')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '工作流设计',
                'verbose_name_plural': '工作流设计',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=50, verbose_name='版本号')),
                ('description', models.TextField(verbose_name='版本描述')),
                ('nodes_snapshot', models.JSONField(verbose_name='节点快照')),
                ('connections_snapshot', models.JSONField(verbose_name='连接快照')),
                ('canvas_snapshot', models.JSONField(default=dict, verbose_name='画布快照')),
                ('changes', models.JSONField(default=list, verbose_name='变更记录')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前版本')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='organizations.workflowdesign')),
            ],
            options={
                'verbose_name': '工作流版本',
                'verbose_name_plural': '工作流版本',
                'ordering': ['-created_at'],
                'unique_together': {('workflow', 'version_name')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_id', models.CharField(max_length=100, unique=True, verbose_name='执行ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('input_data', models.JSONField(default=dict, verbose_name='输入数据')),
                ('output_data', models.JSONField(default=dict, verbose_name='输出数据')),
                ('execution_logs', models.JSONField(default=list, verbose_name='执行日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('current_node', models.CharField(blank=True, max_length=100, verbose_name='当前节点')),
                ('execution_context', models.JSONField(default=dict, verbose_name='执行上下文')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='organizations.workflowdesign')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.workflowversion')),
            ],
            options={
                'verbose_name': '工作流执行',
                'verbose_name_plural': '工作流执行',
                'ordering': ['-started_at'],
            },
        ),
    ]
