# Generated by Django 5.2.1 on 2025-09-29 07:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_workflowdesign_workflowversion_workflowexecution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='租户名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='租户代码')),
                ('domain', models.CharField(max_length=100, unique=True, verbose_name='域名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('active', '激活'), ('suspended', '暂停'), ('inactive', '未激活')], default='inactive', max_length=20, verbose_name='状态')),
                ('max_users', models.IntegerField(default=100, verbose_name='最大用户数')),
                ('max_departments', models.IntegerField(default=50, verbose_name='最大部门数')),
                ('max_employees', models.IntegerField(default=1000, verbose_name='最大员工数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50, verbose_name='部门编码'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', '员工号只能包含大写字母和数字')], verbose_name='员工号'),
        ),
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(max_length=50, verbose_name='职位编码'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant', verbose_name='租户'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant', verbose_name='租户'),
        ),
        migrations.AddField(
            model_name='position',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant', verbose_name='租户'),
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区')),
                ('language', models.CharField(default='zh-cn', max_length=10, verbose_name='语言')),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20, verbose_name='日期格式')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('company_logo', models.URLField(blank=True, verbose_name='公司Logo')),
                ('company_address', models.TextField(blank=True, verbose_name='公司地址')),
                ('enable_employee_self_service', models.BooleanField(default=True, verbose_name='启用员工自助服务')),
                ('enable_workflow_approval', models.BooleanField(default=True, verbose_name='启用工作流审批')),
                ('enable_integration_api', models.BooleanField(default=True, verbose_name='启用集成API')),
                ('password_policy', models.JSONField(default=dict, verbose_name='密码策略')),
                ('session_timeout', models.IntegerField(default=30, verbose_name='会话超时(分钟)')),
                ('enable_two_factor', models.BooleanField(default=False, verbose_name='启用双因子认证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '租户设置',
                'verbose_name_plural': '租户设置',
                'db_table': 'tenant_settings',
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', '基础版'), ('professional', '专业版'), ('enterprise', '企业版')], default='basic', max_length=20, verbose_name='订阅计划')),
                ('status', models.CharField(choices=[('active', '激活'), ('expired', '过期'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='自动续费')),
                ('max_users', models.IntegerField(default=100, verbose_name='最大用户数')),
                ('max_departments', models.IntegerField(default=50, verbose_name='最大部门数')),
                ('max_employees', models.IntegerField(default=1000, verbose_name='最大员工数')),
                ('max_api_calls', models.IntegerField(default=10000, verbose_name='最大API调用数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '租户订阅',
                'verbose_name_plural': '租户订阅',
                'db_table': 'tenant_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('manager', '管理者'), ('user', '普通用户')], default='user', max_length=20, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='可管理用户')),
                ('can_manage_departments', models.BooleanField(default=False, verbose_name='可管理部门')),
                ('can_manage_employees', models.BooleanField(default=False, verbose_name='可管理员工')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='可查看报表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '租户用户',
                'verbose_name_plural': '租户用户',
                'db_table': 'tenant_users',
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
