# Generated by Django 5.2.1 on 2025-09-29 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_tenant_alter_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiontemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant', verbose_name='租户'),
        ),
    ]
