# Generated by Django 5.2.1 on 2025-09-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_analysisconfig_analysisresult_benchmarkdata_and_more'),
    ]

    operations = [
    ]
