# Generated by Django 5.2.1 on 2025-10-05 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_auto_20250929_1642'),
    ]

    operations = [
    ]
