# Generated by Django 5.2.1 on 2025-10-05 09:10

from django.db import migrations
from django.contrib.auth.models import User


def fix_datapermission_user_field(apps, schema_editor):
    """修复DataPermission的user字段"""
    DataPermission = apps.get_model('organizations', 'DataPermission')
    
    # 获取第一个用户作为默认用户
    try:
        default_user = User.objects.first()
        if default_user:
            # 为所有没有user的DataPermission记录设置默认用户
            DataPermission.objects.filter(user__isnull=True).update(user=default_user)
    except Exception as e:
        print(f"Warning: Could not set default user for DataPermission: {e}")


def reverse_fix_datapermission_user_field(apps, schema_editor):
    """反向操作"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20251005_1001'),
    ]

    operations = [
        migrations.RunPython(
            fix_datapermission_user_field,
            reverse_fix_datapermission_user_field,
        ),
    ]
