# Generated by Django 5.2.1 on 2025-09-23 08:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='员工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('department_id', models.IntegerField(verbose_name='部门ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('position_id', models.IntegerField(verbose_name='职位 ID')),
                ('position_name', models.CharField(max_length=100, verbose_name='职位名称')),
                ('position_level', models.IntegerField(default=1, verbose_name='职位级别')),
                ('supervisor_id', models.IntegerField(blank=True, null=True, verbose_name='上级ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='最后同步时间')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['department_name', 'position_level', 'employee_id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('category', models.CharField(choices=[('performance', '工作绩效'), ('ability', '工作能力'), ('attitude', '工作态度'), ('teamwork', '团队合作'), ('innovation', '创新能力')], max_length=20, verbose_name='指标类别')),
                ('description', models.TextField(verbose_name='指标描述')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='权重')),
                ('max_score', models.IntegerField(default=100, verbose_name='最高分数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考核指标',
                'verbose_name_plural': '考核指标',
                'ordering': ['category', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='周期名称')),
                ('description', models.TextField(blank=True, verbose_name='周期描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '考核周期',
                'verbose_name_plural': '考核周期',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('superior', '上级考核下级'), ('peer', '同级互评'), ('subordinate', '下级评价上级')], max_length=20, verbose_name='考核关系')),
                ('evaluation_code', models.CharField(max_length=16, unique=True, verbose_name='考核码')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='考核权重')),
                ('status', models.CharField(choices=[('pending', '待考核'), ('in_progress', '进行中'), ('completed', '已完成'), ('overdue', '已过期')], default='pending', max_length=20, verbose_name='状态')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationcycle', verbose_name='考核周期')),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='being_evaluated', to='evaluations.employee', verbose_name='被考核人')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_tasks', to='evaluations.employee', verbose_name='考核人')),
            ],
            options={
                'verbose_name': '考核任务',
                'verbose_name_plural': '考核任务',
                'ordering': ['-assigned_at'],
                'unique_together': {('cycle', 'evaluator', 'evaluatee', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='总分')),
                ('weighted_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='加权平均分')),
                ('superior_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='上级评分')),
                ('peer_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='同级评分')),
                ('subordinate_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='下级评分')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('is_final', models.BooleanField(default=False, verbose_name='是否最终结果')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='计算时间')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationcycle', verbose_name='考核周期')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.employee', verbose_name='被考核员工')),
            ],
            options={
                'verbose_name': '考核结果',
                'verbose_name_plural': '考核结果',
                'ordering': ['-weighted_score'],
                'unique_together': {('cycle', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='评价意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationindicator', verbose_name='考核指标')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationtask', verbose_name='考核任务')),
            ],
            options={
                'verbose_name': '考核评分',
                'verbose_name_plural': '考核评分',
                'ordering': ['-created_at'],
                'unique_together': {('task', 'indicator')},
            },
        ),
    ]
