# Generated by Django 5.2.1 on 2025-09-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(default="active", max_length=20, verbose_name="状态"),
        ),
    ]
