# Generated by Django 5.2.1 on 2025-09-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0006_remove_evaluation_code_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationscore",
            name="weighted_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="根据评价人职级权重计算的加权评分",
                max_digits=5,
                null=True,
                verbose_name="加权评分",
            ),
        ),
        migrations.CreateModel(
            name="PositionWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_id",
                    models.IntegerField(
                        help_text="对应组织架构系统中的职位ID", verbose_name="职位ID"
                    ),
                ),
                (
                    "position_name",
                    models.CharField(
                        help_text="职位名称，用于显示", max_length=100, verbose_name="职位名称"
                    ),
                ),
                (
                    "position_level",
                    models.IntegerField(
                        default=0, help_text="职位级别，数字越大级别越高", verbose_name="职位级别"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="该职级的评分权重",
                        max_digits=5,
                        verbose_name="权重",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "职级权重",
                "verbose_name_plural": "职级权重",
                "unique_together": {("position_id",)},
            },
        ),
    ]
