# Generated by Django 5.2.1 on 2025-09-29 03:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_evaluationscore_weighted_score_positionweight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCycleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='周期类型名称')),
                ('cycle_type', models.CharField(choices=[('annual', '年度'), ('quarterly', '季度'), ('monthly', '月度'), ('weekly', '周度'), ('custom', '自定义')], max_length=20, verbose_name='周期类型')),
                ('duration_days', models.IntegerField(help_text='一个完整周期的天数', verbose_name='周期天数')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评估周期类型',
                'verbose_name_plural': '评估周期类型',
                'ordering': ['duration_days'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='维度名称')),
                ('dimension_type', models.CharField(choices=[('capability', '能力维度'), ('attitude', '态度维度'), ('performance', '业绩维度'), ('innovation', '创新维度'), ('leadership', '领导力维度'), ('teamwork', '团队合作维度'), ('customer_service', '客户服务维度'), ('custom', '自定义维度')], max_length=20, verbose_name='维度类型')),
                ('description', models.TextField(blank=True, verbose_name='维度描述')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='维度权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评估维度',
                'verbose_name_plural': '评估维度',
                'ordering': ['-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='方法名称')),
                ('method_type', models.CharField(choices=[('360_degree', '360度评估'), ('okr', 'OKR目标与关键结果'), ('kpi', 'KPI关键绩效指标'), ('mbo', 'MBO目标管理'), ('bsc', 'BSC平衡计分卡'), ('custom', '自定义方法')], max_length=20, verbose_name='方法类型')),
                ('description', models.TextField(blank=True, verbose_name='方法描述')),
                ('configuration', models.JSONField(default=dict, help_text='评估方法的具体配置', verbose_name='方法配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评估方法',
                'verbose_name_plural': '评估方法',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('evaluation_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationmethod', verbose_name='评估方法')),
            ],
            options={
                'verbose_name': '评估模板',
                'verbose_name_plural': '评估模板',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MultidimensionalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='指标名称')),
                ('description', models.TextField(blank=True, verbose_name='指标描述')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='指标权重')),
                ('scoring_criteria', models.JSONField(default=dict, help_text='评分标准和规则', verbose_name='评分标准')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationdimension', verbose_name='所属维度')),
            ],
            options={
                'verbose_name': '多维度评估指标',
                'verbose_name_plural': '多维度评估指标',
                'ordering': ['dimension', '-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='权重')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationdimension', verbose_name='维度')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationtemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '模板维度',
                'verbose_name_plural': '模板维度',
                'ordering': ['order'],
                'unique_together': {('template', 'dimension')},
            },
        ),
        migrations.AddField(
            model_name='evaluationtemplate',
            name='dimensions',
            field=models.ManyToManyField(through='evaluations.TemplateDimension', to='evaluations.evaluationdimension', verbose_name='包含维度'),
        ),
        migrations.CreateModel(
            name='MultidimensionalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.JSONField(default=dict, help_text='各维度的评分结果', verbose_name='维度评分')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='总分')),
                ('weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='加权分')),
                ('comments', models.TextField(blank=True, verbose_name='评价意见')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('reviewed', '已审核'), ('finalized', '已确定')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationcycle', verbose_name='考核周期')),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multidimensional_evaluated', to='evaluations.employee', verbose_name='被评价人')),
                ('evaluation_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationmethod', verbose_name='评估方法')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multidimensional_evaluations', to='evaluations.employee', verbose_name='评价人')),
            ],
            options={
                'verbose_name': '多维度评估',
                'verbose_name_plural': '多维度评估',
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'evaluator', 'evaluatee', 'evaluation_method')},
            },
        ),
    ]
