# Generated by Django 5.2.1 on 2025-09-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='员工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('department_id', models.IntegerField(verbose_name='部门ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('position_id', models.IntegerField(verbose_name='职位ID')),
                ('position_name', models.CharField(max_length=100, verbose_name='职位名称')),
                ('position_level', models.IntegerField(default=1, verbose_name='职位级别')),
                ('supervisor_id', models.IntegerField(blank=True, null=True, verbose_name='上级ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='最后同步时间')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['department_name', 'position_level', 'employee_id'],
            },
        ),
    ]
